# -*- coding: utf-8 -*-
"""augment_dataset4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QXQ8YQfVLqIxhiFieVY11SAxAHnApap
"""

import json
import torch
import re
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

MODEL_NAME = "facebook/nllb-200-distilled-600M"

LT_CODE = "lit_Latn"
EN_CODE = "eng_Latn"

INPUT_PATH  = "train.jsonl"
OUTPUT_PATH = "train_augmented.jsonl"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Loading NLLB model...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME).to(DEVICE)

model.eval()

print("Model loaded.\n")


# ----------------------------
# helpers
# ----------------------------

def split_sentences(text):
    # simple but stable splitter for Lithuanian structured text
    return re.split(r"(?<=[.!?])\s+", text.strip())


def translate(text, src_lang, tgt_lang, max_length=512):
    tokenizer.src_lang = src_lang

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=max_length,
    ).to(DEVICE)

    forced_bos_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            forced_bos_token_id=forced_bos_token_id,
            max_length=max_length,
            num_beams=5,   # slightly stronger decoding for stability
        )

    return tokenizer.decode(output[0], skip_special_tokens=True)


def similarity_filter(original, augmented):
    """
    Reject outputs that are too different structurally.
    This prevents hallucinated rewrites.
    """
    orig_words = set(original.lower().split())
    aug_words  = set(augmented.lower().split())

    if len(aug_words) == 0:
        return False

    overlap = len(orig_words & aug_words) / len(orig_words)

    # too low = hallucination risk
    # too high = useless copy
    return 0.55 <= overlap <= 0.95


def back_translate_structured(text):
    """
    Sentence-level controlled back-translation.
    """
    sentences = split_sentences(text)

    rebuilt = []

    for s in sentences:
        if len(s.strip()) < 20:
            rebuilt.append(s)
            continue

        en = translate(s, LT_CODE, EN_CODE)
        lt = translate(en, EN_CODE, LT_CODE)

        rebuilt.append(lt)

    return " ".join(rebuilt)


# ----------------------------
# load dataset
# ----------------------------

original = []
with open(INPUT_PATH, "r", encoding="utf-8") as f:
    for line in f:
        original.append(json.loads(line))


augmented = []
failed = []

print(f"Loaded {len(original)} examples\n")

# ----------------------------
# augmentation loop
# ----------------------------

for i, ex in enumerate(original, 1):
    response = ex["response"]

    print(f"[{i}/{len(original)}] {ex['instruction']}")

    try:
        bt = back_translate_structured(response)

        # quality filters
        if (
            bt.strip()
            and bt != response
            and similarity_filter(response, bt)
            and len(bt.split()) > 0.7 * len(response.split())
        ):
            augmented.append({
                "instruction": ex["instruction"],
                "response": bt
            })
            print("OK")
        else:
            print("SKIP (filtered)")

    except Exception as e:
        print("ERROR:", e)
        failed.append(ex["instruction"])


# ----------------------------
# save
# ----------------------------

combined = original + augmented

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    for item in combined:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("\n====================")
print("DONE")
print("====================")
print("Original:", len(original))
print("Augmented:", len(augmented))
print("Failed:", len(failed))
print("Output:", OUTPUT_PATH)