# -*- coding: utf-8 -*-
"""evaluate_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCiDHEhqJ3zIR6uWgb_gg59BfJq9rJQz
"""

import json
import torch
import math
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
from peft import PeftModel

BASE_MODEL  = "microsoft/phi-2"
ADAPTER_DIR = "./finetuned_model"
TEST_PATH   = "test.jsonl"
MAX_LEN     = 512

TORCH_DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(ADAPTER_DIR, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("Loading base model")
config = AutoConfig.from_pretrained(BASE_MODEL, trust_remote_code=True)
config.pad_token_id = tokenizer.pad_token_id

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    config            = config,
    torch_dtype       = TORCH_DTYPE,
    device_map        = "auto",
    trust_remote_code = True,
)
base_model.eval()

# Loading fine-tuned model

print("Loading fine-tuned model...")
finetuned_model = PeftModel.from_pretrained(base_model, ADAPTER_DIR)
finetuned_model.eval()

# BLEU-1 score: measuring word-level overlap

def bleu1(reference, hypothesis):
    """
    Compute unigram BLEU score between reference and hypothesis strings.
    BLEU-1 counts how many words in the hypothesis appear in the reference.
    Score is between 0 (no overlap) and 1 (perfect match).
    """
    ref_words  = set(reference.lower().split())
    hyp_words  = hypothesis.lower().split()
    if not hyp_words:
        return 0.0
    matches = sum(1 for w in hyp_words if w in ref_words)
    return matches / len(hyp_words)

# Generation helper

def generate(model, prompt):
    inputs = tokenizer(
        prompt,
        return_tensors = "pt",
        truncation     = True,
        max_length     = MAX_LEN,
    )
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens     = 150,
            temperature        = 0.3,
            top_p              = 0.9,
            do_sample          = True,
            repetition_penalty = 1.3,
            eos_token_id       = tokenizer.eos_token_id,
            pad_token_id       = tokenizer.eos_token_id,
        )
    return tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    ).strip()


# Perplexity

def compute_perplexity(model, examples):
    total_loss = 0.0
    count      = 0
    model.eval()
    for ex in examples:
        text = f"Instruct: {ex['instruction']}\nOutput: {ex['response']}<|endoftext|>"
        inputs = tokenizer(
            text,
            return_tensors = "pt",
            truncation     = True,
            max_length     = MAX_LEN,
        ).to(model.device)
        with torch.no_grad():
            out = model(**inputs, labels=inputs["input_ids"])
            total_loss += out.loss.item()
            count      += 1
    return math.exp(total_loss / count)

# Loading test set

test_examples = []
with open(TEST_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            test_examples.append(json.loads(line))

print(f"\nLoaded {len(test_examples)} test examples.")

# Comparison

sample_places = ["Vilnius", "Trakai", "Dūkštas", "Gadūnavas"]

print("\n" + "=" * 70)
print("SIDE-BY-SIDE: BASE MODEL vs FINE-TUNED MODEL")
print("=" * 70)

for place in sample_places:
    prompt = f"Instruct: Apibūdink: {place}\nOutput:"
    base_out      = generate(base_model, prompt)
    finetuned_out = generate(finetuned_model, prompt)

    print(f"PLACE: {place}")
    print(f"\n[BASE MODEL]")
    print(base_out[:300])
    print(f"\n[FINE-TUNED]")
    print(finetuned_out[:300])

# Evaluation

print("\n\n" + "=" * 70)
print("QUANTITATIVE EVALUATION ON TEST SET")
print("=" * 70)

print("\nComputing perplexity...")
base_ppl      = compute_perplexity(base_model, test_examples)
finetuned_ppl = compute_perplexity(finetuned_model, test_examples)

print("\nComputing BLEU-1 scores...")
base_bleu_scores      = []
finetuned_bleu_scores = []

for ex in test_examples:
    prompt    = f"Instruct: {ex['instruction']}\nOutput:"
    reference = ex["response"]

    base_gen      = generate(base_model, prompt)
    finetuned_gen = generate(finetuned_model, prompt)

    base_bleu_scores.append(bleu1(reference, base_gen))
    finetuned_bleu_scores.append(bleu1(reference, finetuned_gen))

avg_base_bleu      = sum(base_bleu_scores) / len(base_bleu_scores)
avg_finetuned_bleu = sum(finetuned_bleu_scores) / len(finetuned_bleu_scores)

print(f"{'Metric':<30} {'Base phi-2':>15} {'Fine-tuned':>15}")
print(f"{'─'*70}")
print(f"{'Perplexity (↓ better)':<30} {base_ppl:>15.2f} {finetuned_ppl:>15.2f}")
print(f"{'BLEU-1 (↑ better)':<30} {avg_base_bleu:>15.4f} {avg_finetuned_bleu:>15.4f}")
print(f"{'─'*70}")
print(f"\nPerplexity improvement: {((base_ppl - finetuned_ppl) / base_ppl * 100):.1f}%")
print(f"BLEU-1 improvement:     {((avg_finetuned_bleu - avg_base_bleu) / max(avg_base_bleu, 1e-9) * 100):.1f}%")