# -*- coding: utf-8 -*-
"""finetune13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRPO_MJKJoZ8EsZCVmV0nSwJU1xqkvb-
"""

import json
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoConfig,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer

MODEL_NAME   = "microsoft/phi-2"
DATASET_PATH = "train_augmented.jsonl"
# After running augment_dataset.py, change to "train_augmented.jsonl"

OUTPUT_DIR   = "./finetuned_model"

USE_GPU     = torch.cuda.is_available()
TORCH_DTYPE = torch.float16 if USE_GPU else torch.float32

# LoRA hyperparameters
LORA_RANK    = 32
LORA_ALPHA   = 64
LORA_DROPOUT = 0.05
LORA_TARGET  = ["q_proj", "k_proj", "v_proj", "dense", "fc1", "fc2"]

# Training hyperparameters
NUM_EPOCHS    = 6
BATCH_SIZE    = 1
GRAD_ACCUM    = 8
LEARNING_RATE = 5e-5
MAX_SEQ_LEN   = 512


def load_jsonl(filepath):
    examples = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))
    return examples


def format_example(example):
    text = (
        f"Instruct: {example['instruction']}\n"
        f"Output: {example['response']}<|endoftext|>"
    )
    return {"text": text}


def prepare_dataset(filepath):
    raw       = load_jsonl(filepath)
    formatted = [format_example(ex) for ex in raw]
    dataset   = Dataset.from_list(formatted)
    print(f"Dataset loaded: {len(dataset)} examples")
    print("\nExample formatted input:")
    print(dataset[0]["text"])
    print("-" * 50)
    return dataset


def load_model_and_tokenizer(model_name):
    print(f"\nLoading model: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(
        model_name, trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    config = AutoConfig.from_pretrained(
        model_name, trust_remote_code=True,
    )
    config.pad_token_id = tokenizer.pad_token_id

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        config            = config,
        torch_dtype       = TORCH_DTYPE,
        device_map        = "auto",
        trust_remote_code = True,
    )
    model.config.use_cache = False
    model.gradient_checkpointing_enable()

    print(f"Model loaded. Total parameters: {model.num_parameters():,}")
    return model, tokenizer


def apply_lora(model):
    lora_config = LoraConfig(
        task_type      = TaskType.CAUSAL_LM,
        r              = LORA_RANK,
        lora_alpha     = LORA_ALPHA,
        target_modules = LORA_TARGET,
        lora_dropout   = LORA_DROPOUT,
        bias           = "none",
    )
    model = get_peft_model(model, lora_config)
    trainable, total = model.get_nb_trainable_parameters()
    print(f"\nLoRA applied:")
    print(f"  Trainable parameters: {trainable:,}")
    print(f"  Total parameters:     {total:,}")
    print(f"  Trainable ratio:      {100 * trainable / total:.3f}%")
    return model


def train(model, tokenizer, dataset):
    training_args = TrainingArguments(
        output_dir                  = OUTPUT_DIR,
        num_train_epochs            = NUM_EPOCHS,
        per_device_train_batch_size = BATCH_SIZE,
        gradient_accumulation_steps = GRAD_ACCUM,
        learning_rate               = LEARNING_RATE,
        fp16                        = USE_GPU,
        logging_steps               = 5,
        save_strategy               = "epoch",
        optim                       = "adamw_torch",
        warmup_ratio                = 0.10,
        lr_scheduler_type           = "warmup_stable_decay",

        lr_scheduler_kwargs = {
            "num_stable_steps": 216,
            "num_decay_steps": 94,
            },

        weight_decay                = 0.01,
        label_smoothing_factor      = 0.0,
        # Removed label smoothing — with only ~285 examples the model needs
        # to learn confidently from each example, not soft targets.
        report_to                   = "none",
    )

    trainer = SFTTrainer(
        model              = model,
        tokenizer          = tokenizer,
        train_dataset      = dataset,
        dataset_text_field = "text",
        max_seq_length     = MAX_SEQ_LEN,
        args               = training_args,
        packing            = False,
    )

    print(f"\nStarting training...")
    print(f"  Epochs:        {NUM_EPOCHS}")
    print(f"  Batch size:    {BATCH_SIZE} (effective: {BATCH_SIZE * GRAD_ACCUM})")
    print(f"  Learning rate: {LEARNING_RATE}")
    print(f"  Examples:      {len(dataset)}")
    print()

    trainer.train()

    # Diagnostic: verify LoRA actually updated its weights
    print("\nLoRA weight check (should be non-zero if training worked):")
    for name, param in model.named_parameters():
        if "lora" in name.lower():
            print(f"  {name}: mean={param.abs().mean().item():.6f}")
            break

    print("\nTraining complete. Saving model...")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"Saved to: {OUTPUT_DIR}")
    return trainer


def evaluate_on_test_set(model, tokenizer, test_path="test.jsonl"):
    import math, os
    if not os.path.exists(test_path):
        print(f"\nNo test file at {test_path}, skipping.")
        return

    model.eval()
    test_examples = load_jsonl(test_path)
    total_loss    = 0.0
    count         = 0

    print(f"\nEvaluating on {len(test_examples)} test examples...")

    for ex in test_examples:
        text = (
            f"Instruct: {ex['instruction']}\n"
            f"Output: {ex['response']}<|endoftext|>"
        )
        inputs = tokenizer(
            text,
            return_tensors = "pt",
            truncation     = True,
            max_length     = MAX_SEQ_LEN,
        ).to(model.device)

        with torch.no_grad():
            outputs     = model(**inputs, labels=inputs["input_ids"])
            total_loss += outputs.loss.item()
            count      += 1

    avg_loss   = total_loss / count
    perplexity = math.exp(avg_loss)

    print(f"EVALUATION RESULTS (test set)")
    print(f"{'='*50}")
    print(f"  Examples evaluated: {count}")
    print(f"  Average loss:       {avg_loss:.4f}")
    print(f"  Perplexity:         {perplexity:.2f}")
    print(f"  (lower = better generalisation)")


def test_model(model, tokenizer):
    model.eval()

    # Use small obscure towns from the test set, NOT Vilnius or Kaunas.
    # phi-2 has strong English pretraining knowledge about major cities,
    # which overwhelms LoRA during generation for well-known places.
    # Obscure towns have no conflicting English base knowledge, so LoRA
    # dominates and produces Lithuanian output as trained.
    test_prompts = [
        "Instruct: Apibūdink: Dūkštas\nOutput:",
        "Instruct: Apibūdink: Gadūnavas\nOutput:",
        "Instruct: Apibūdink: Bartninkai\nOutput:",
        "Instruct: Apibūdink: Kvėdarna\nOutput:",
        "Instruct: Apibūdink: Veliuona\nOutput:",
    ]

    temperatures = [0.0, 0.1, 0.2, 0.3]

    print("\nTEMPERATURE SWEEP (first prompt only)")
    print("=" * 70)

    sweep_prompt = test_prompts[0]
    place        = sweep_prompt.split("Apibūdink: ")[1].split("\n")[0]
    print(f"Prompt: Apibūdink {place}\n")

    for temp in temperatures:
        inputs = tokenizer(
            sweep_prompt,
            return_tensors = "pt",
            truncation     = True,
            max_length     = MAX_SEQ_LEN,
        ).to(model.device)

        with torch.no_grad():
            if temp == 0.0:
                outputs = model.generate(
                    **inputs,
                    max_new_tokens     = 150,
                    do_sample          = False,
                    repetition_penalty = 1.1,
                    eos_token_id       = tokenizer.eos_token_id,
                    pad_token_id       = tokenizer.eos_token_id,
                )
            else:
                outputs = model.generate(
                    **inputs,
                    max_new_tokens     = 150,
                    temperature        = temp,
                    top_p              = 0.9,
                    do_sample          = True,
                    repetition_penalty = 1.1,
                    eos_token_id       = tokenizer.eos_token_id,
                    pad_token_id       = tokenizer.eos_token_id,
                )

        generated = tokenizer.decode(
            outputs[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True,
        )
        label = "greedy (temp=0.0)" if temp == 0.0 else f"temp={temp}"
        print(f"[{label}]")
        print(generated.strip()[:300])
        print()

    print("\nFULL INFERENCE TEST (greedy decoding)")
    print("=" * 60)

    for prompt in test_prompts:
        inputs = tokenizer(
            prompt,
            return_tensors = "pt",
            truncation     = True,
            max_length     = MAX_SEQ_LEN,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens     = 200,
                do_sample          = False,
                repetition_penalty = 1.1,
                eos_token_id       = tokenizer.eos_token_id,
                pad_token_id       = tokenizer.eos_token_id,
            )

        generated = tokenizer.decode(
            outputs[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True,
        )
        place = prompt.split("Apibūdink: ")[1].split("\n")[0]
        print(f"\n[{place}]")
        print(generated.strip())
        print("-" * 60)


if __name__ == "__main__":
    print("=" * 60)
    print("Lithuanian LLM Fine-Tuning with LoRA (phi-2)")
    print("=" * 60)

    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
    else:
        print("WARNING: No GPU detected.")
    print()

    dataset          = prepare_dataset(DATASET_PATH)
    model, tokenizer = load_model_and_tokenizer(MODEL_NAME)
    model            = apply_lora(model)
    trainer          = train(model, tokenizer, dataset)
    evaluate_on_test_set(model, tokenizer, "test.jsonl")
    test_model(model, tokenizer)