# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvp5WM424AKud4lAxtDE_SVQRuyE3GZT
"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
from peft import PeftModel

BASE_MODEL  = "microsoft/phi-2"
ADAPTER_DIR = "./finetuned_model"
MAX_LEN     = 512

# Loading model

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(
    ADAPTER_DIR,           # Use the saved tokenizer, not the base one
    trust_remote_code=True,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("Loading base model...")
config = AutoConfig.from_pretrained(BASE_MODEL, trust_remote_code=True)
config.pad_token_id = tokenizer.pad_token_id

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    config            = config,
    torch_dtype       = torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map        = "auto",
    trust_remote_code = True,
)

print("Loading LoRA adapter...")
model = PeftModel.from_pretrained(base_model, ADAPTER_DIR)
model.eval()
print("Ready.\n")

# Test prompts
# Format: "Instruct: Apibūdink: <place>\nOutput:"

test_prompts = [
    "Instruct: Apibūdink: Vilnius\nOutput:",
    "Instruct: Apibūdink: Kaunas\nOutput:",
    "Instruct: Apibūdink: Dūkštas\nOutput:",
    "Instruct: Apibūdink: Gadūnavas\nOutput:",
    "Instruct: Apibūdink: Trakai\nOutput:",
]

print("FINE-TUNED MODEL OUTPUT")
print("=" * 60)

for prompt in test_prompts:
    inputs = tokenizer(
        prompt,
        return_tensors = "pt",
        truncation     = True,
        max_length     = MAX_LEN,
    )
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens     = 200,
            temperature        = 0.3,
            top_p              = 0.9,
            do_sample          = True,
            repetition_penalty = 1.3,
            eos_token_id       = tokenizer.eos_token_id,
            pad_token_id       = tokenizer.eos_token_id,
        )

    # Decode only the newly generated part
    generated = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    )

    place = prompt.split("Apibūdink: ")[1].split("\n")[0]
    print(f"\n[{place}]")
    print(generated.strip())
    print("-" * 60)